# Generated by Django 5.1.7 on 2025-04-26 21:15

import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=registration.models.custom_profile_picture_path),
        ),
    ]
